/*
 * This file is autogenerated by cbindgen. Do not modify this file manually.
 * To regenerate this file, run:
 * ```
 * cbindgen --config cbindgen.toml --crate monero-rust --output monero-rust.h
 * ```
 * from the project root.
 *
 * For more information, see the project documentation or contact the project maintainer.
 */


#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


#define CHACHA_IV_SIZE 8

#define CHACHA_KEY_SIZE 32

#define NONCE_SIZE 12

#define SALT_SIZE 32

typedef struct WalletState WalletState;

/**
 * # Safety
 * ptr must be from this library
 */
void free_string(char *ptr);

char *generate_address(const char *mnemonic, uint8_t network, uint32_t account, uint32_t index);

char *generate_mnemonic(uint8_t language);

/**
 * Estimate tx fee for given priority and amount.
 * Returns fee in piconeros or negative error code.
 */
int64_t wallet_estimate_fee(const struct WalletState *wallet, uint8_t priority, uint64_t amount);

/**
 * Export key images to file. Returns count on success,
 * -1 bad wallet, -2 bad filename, -3 closed, -4 export failed, -5 panic.
 */
int64_t wallet_export_key_images(const struct WalletState *wallet,
                                 const char *filename,
                                 int32_t all);

/**
 * # Safety
 * Must only be called once per wallet allocated by wallet_load().
 */
void wallet_free(struct WalletState *wallet);

/**
 * Freeze an output by key image. Returns 0 on success,
 * -1 bad wallet, -2 bad key_image, -3 closed, -4 not found, -5 panic.
 */
int32_t wallet_freeze_output(struct WalletState *wallet, const uint8_t *key_image);

/**
 * Returns JSON array of all txids as hex strings. Caller must free with free_string().
 */
char *wallet_get_all_txids(const struct WalletState *wallet);

/**
 * Returns JSON array of all transactions. Caller must free with free_string().
 */
char *wallet_get_all_txs(const struct WalletState *wallet);

/**
 * Returns total balance in piconeros, 0 on null/panic.
 */
uint64_t wallet_get_balance(const struct WalletState *wallet);

/**
 * Returns current scanned height, 0 on null/panic.
 */
uint64_t wallet_get_current_height(const struct WalletState *wallet);

/**
 * Returns daemon height, 0 on null/panic.
 */
uint64_t wallet_get_daemon_height(const struct WalletState *wallet);

/**
 * Returns outputs as JSON. Set include_spent=1 to include spent outputs.
 * Set refresh=1 to refresh from daemon first.
 * Returns null on error. Caller must free with free_string().
 */
char *wallet_get_outputs(struct WalletState *wallet, int32_t include_spent, int32_t refresh);

/**
 * Returns total output count, 0 on null/panic.
 */
uint64_t wallet_get_outputs_count(const struct WalletState *wallet);

/**
 * # Safety
 * Caller must free with free_string(). Returns null if path isn't valid UTF-8.
 */
char *wallet_get_path(const struct WalletState *wallet);

/**
 * # Safety
 * Caller must free with free_string(). Returns null for view-only wallets.
 */
char *wallet_get_private_spend_key(const struct WalletState *wallet);

/**
 * # Safety
 * Caller must free with free_string().
 */
char *wallet_get_private_view_key(const struct WalletState *wallet);

/**
 * # Safety
 * Caller must free with free_string().
 */
char *wallet_get_public_spend_key(const struct WalletState *wallet);

/**
 * # Safety
 * Caller must free with free_string().
 */
char *wallet_get_public_view_key(const struct WalletState *wallet);

/**
 * Returns refresh height, 0 on null/panic.
 */
uint64_t wallet_get_refresh_from_height(const struct WalletState *wallet);

/**
 * # Safety
 * Caller must free with free_string(). Returns null for view-only wallets.
 */
char *wallet_get_seed(const struct WalletState *wallet);

/**
 * # Safety
 * Caller must free with free_string().
 */
char *wallet_get_seed_language(const struct WalletState *wallet);

/**
 * Returns spent output count, 0 on null/panic.
 */
uint64_t wallet_get_spent_outputs_count(const struct WalletState *wallet);

/**
 * Returns transaction count, 0 on null/panic.
 */
uint64_t wallet_get_transaction_count(const struct WalletState *wallet);

/**
 * Returns JSON for a single transaction, or null if not found.
 * Caller must free with free_string().
 */
char *wallet_get_tx(const struct WalletState *wallet, const uint8_t *txid);

/**
 * Returns tx private key as hex string for an outgoing transaction, or null if not found.
 * Caller must free with free_string().
 */
char *wallet_get_tx_key(const struct WalletState *wallet, const uint8_t *txid);

/**
 * Returns JSON array of transactions. Null entries for missing txids.
 * Caller must free with free_string().
 */
char *wallet_get_txs(const struct WalletState *wallet, const uint8_t *txids, uint64_t count);

/**
 * Returns unlocked (spendable) balance in piconeros, 0 on null/panic.
 */
uint64_t wallet_get_unlocked_balance(const struct WalletState *wallet);

/**
 * Import key images from file. Returns (newly_spent << 32) | already_spent on success,
 * -1 bad wallet, -2 bad filename, -3 closed, -4 import failed, -5 panic.
 */
int64_t wallet_import_key_images(struct WalletState *wallet, const char *filename);

/**
 * Returns 1 if closed, 0 if open, -1 on null pointer, -5 on panic.
 */
int32_t wallet_is_closed(const struct WalletState *wallet);

/**
 * Returns 1 if syncing, 0 if not, -1 null, -5 panic.
 */
int32_t wallet_is_syncing(const struct WalletState *wallet);

/**
 * Returns 1 if view-only, 0 if normal, -1 on null pointer, -5 on panic.
 */
int32_t wallet_is_view_only(const struct WalletState *wallet);

/**
 * # Safety
 * Path and password must be null-terminated UTF-8. Caller must free with wallet_free().
 */
struct WalletState *wallet_load(const char *path, const char *password);

/**
 * Refreshes output unlock status from daemon. Returns 0 on success,
 * -1 null, -2 not connected, -3 closed, -4 error, -5 panic.
 */
int32_t wallet_refresh_outputs(struct WalletState *wallet);

/**
 * Refreshes transaction confirmation counts from daemon. Returns 0 on success,
 * -1 null, -2 not connected, -3 closed, -4 error, -5 panic.
 */
int32_t wallet_refresh_transactions(struct WalletState *wallet);

/**
 * Clears outputs/txs and resets to refresh height. Returns 0 on success, -1 null, -5 panic.
 */
int32_t wallet_rescan_blockchain(struct WalletState *wallet);

/**
 * # Safety
 * Wallet pointer must be valid. Password must be null-terminated UTF-8.
 */
int32_t wallet_save(const struct WalletState *wallet, const char *password);

/**
 * Sets refresh height. Returns 0 on success, -1 null, -5 panic.
 */
int32_t wallet_set_refresh_from_height(struct WalletState *wallet, uint64_t height);

/**
 * Starts syncing. Returns 0 on success, -1 null, -2 not connected, -3 closed, -5 panic.
 */
int32_t wallet_start_syncing(struct WalletState *wallet);

/**
 * Stops syncing. Returns 0 on success, -1 null, -5 panic.
 */
int32_t wallet_stop_syncing(struct WalletState *wallet);

/**
 * Stores a tx key for an outgoing transaction.
 * Returns 0 on success, -1 null wallet, -2 null txid, -3 null key,
 * -4 invalid additional_keys, -5 closed, -6 limit exceeded, -7 panic.
 */
int32_t wallet_store_tx_key(struct WalletState *wallet,
                            const uint8_t *txid,
                            const uint8_t *tx_private_key,
                            const uint8_t *additional_keys,
                            uint64_t additional_keys_count);

/**
 * Scans one block. Returns 1 if scanned, 0 if synced, -1 null, -2 not connected, -3 closed, -4 error, -5 panic.
 */
int32_t wallet_sync_once(struct WalletState *wallet);

/**
 * Thaw (unfreeze) an output by key image. Returns 0 on success,
 * -1 bad wallet, -2 bad key_image, -3 closed, -4 not found, -5 panic.
 */
int32_t wallet_thaw_output(struct WalletState *wallet, const uint8_t *key_image);
