/*
 * This file is autogenerated by cbindgen. Do not modify this file manually.
 * To regenerate this file, run:
 * ```
 * cbindgen --config cbindgen.toml --crate monero-rust --output monero-rust.h
 * ```
 * from the project root.
 *
 * For more information, see the project documentation or contact the project maintainer.
 */


#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


typedef struct WalletState WalletState;

/**
 * # Safety
 * ptr must be from this library
 */
void free_string(char *ptr);

char *generate_address(const char *mnemonic, uint8_t network, uint32_t account, uint32_t index);

char *generate_mnemonic(uint8_t language);

/**
 * # Safety
 * Must only be called once per wallet allocated by wallet_load().
 */
void wallet_free(struct WalletState *wallet);

/**
 * # Safety
 * Caller must free with free_string(). Returns null if path isn't valid UTF-8.
 */
char *wallet_get_path(const struct WalletState *wallet);

/**
 * # Safety
 * Caller must free with free_string(). Returns null for view-only wallets.
 */
char *wallet_get_private_spend_key(const struct WalletState *wallet);

/**
 * # Safety
 * Caller must free with free_string().
 */
char *wallet_get_private_view_key(const struct WalletState *wallet);

/**
 * # Safety
 * Caller must free with free_string().
 */
char *wallet_get_public_spend_key(const struct WalletState *wallet);

/**
 * # Safety
 * Caller must free with free_string().
 */
char *wallet_get_public_view_key(const struct WalletState *wallet);

/**
 * # Safety
 * Caller must free with free_string(). Returns null for view-only wallets.
 */
char *wallet_get_seed(const struct WalletState *wallet);

/**
 * # Safety
 * Caller must free with free_string().
 */
char *wallet_get_seed_language(const struct WalletState *wallet);

/**
 * Returns 1 if closed, 0 if open, -1 on null pointer, -5 on panic.
 */
int32_t wallet_is_closed(const struct WalletState *wallet);

/**
 * Returns 1 if view-only, 0 if normal, -1 on null pointer, -5 on panic.
 */
int32_t wallet_is_view_only(const struct WalletState *wallet);

/**
 * # Safety
 * Path and password must be null-terminated UTF-8. Caller must free with wallet_free().
 */
struct WalletState *wallet_load(const char *path, const char *password);

/**
 * # Safety
 * Wallet pointer must be valid. Password must be null-terminated UTF-8.
 */
int32_t wallet_save(const struct WalletState *wallet, const char *password);
