[package]
name = "monero-payment-proofs"
version = "0.1.0"
description = "Payment proofs for the Monero protocol"
license = "MIT"
authors = ["Luke Parker <lukeparker5132@gmail.com>"]
edition = "2021"

[dependencies]
std-shims = { version = "0.1.4", default-features = false }

zeroize = { version = "^1.5", default-features = false, features = ["zeroize_derive"] }
rand_core = { version = "0.6", default-features = false }

sha3 = { version = "0.10", default-features = false }
curve25519-dalek = { version = "^3.2", default-features = false, features = ["std"] }

monero-serai = { path = "../../monero-serai-mirror", default-features = false }
monero-generators = { path = "../../monero-serai-mirror/generators" }

[features]
std = [
  "std-shims/std",

  "zeroize/std",
  "rand_core/std",

  "sha3/std",
]
default = ["std"]
