import 'signal_types.dart';

/// Maps RustSignal type names (as sent by Rust) to their handler functions.
/// Passed to initializeBareFfi() during startup.
final Map<String, void Function(String json)> rustSignalHandlers = {
  'MoneroTestResponse': MoneroTestResponse.handleFromRust,
  'WalletCreatedResponse': WalletCreatedResponse.handleFromRust,
  'SyncProgressResponse': SyncProgressResponse.handleFromRust,
  'BalanceResponse': BalanceResponse.handleFromRust,
  'TransactionCreatedResponse': TransactionCreatedResponse.handleFromRust,
  'SeedGeneratedResponse': SeedGeneratedResponse.handleFromRust,
  'SeedBirthdayResponse': SeedBirthdayResponse.handleFromRust,
  'BlockHeightFromTimestampResponse': BlockHeightFromTimestampResponse.handleFromRust,
  'AddressDerivedResponse': AddressDerivedResponse.handleFromRust,
  'SubaddressDerivedResponse': SubaddressDerivedResponse.handleFromRust,
  'KeysDerivedResponse': KeysDerivedResponse.handleFromRust,
  'BlockScanResponse': BlockScanResponse.handleFromRust,
  'TransactionBroadcastResponse': TransactionBroadcastResponse.handleFromRust,
  'DaemonHeightResponse': DaemonHeightResponse.handleFromRust,
  'SpentStatusUpdatedResponse': SpentStatusUpdatedResponse.handleFromRust,
  'MempoolScanResponse': MempoolScanResponse.handleFromRust,
  'OutProofGeneratedResponse': OutProofGeneratedResponse.handleFromRust,
  'WalletDataSavedResponse': WalletDataSavedResponse.handleFromRust,
  'WalletDataLoadedResponse': WalletDataLoadedResponse.handleFromRust,
  'EncryptionKeyDerivedResponse': EncryptionKeyDerivedResponse.handleFromRust,
  'MultiWalletScanResponse': MultiWalletScanResponse.handleFromRust,
  'BlockHashesResponse': BlockHashesResponse.handleFromRust,
  'PendingStateResponse': PendingStateResponse.handleFromRust,
  'ReorgDetectedResponse': ReorgDetectedResponse.handleFromRust,
  'DoubleSpendDetectedResponse': DoubleSpendDetectedResponse.handleFromRust,
  'Bip39LegacySeedResponse': Bip39LegacySeedResponse.handleFromRust,
  'FreezeThawResponse': FreezeThawResponse.handleFromRust,
  'TransactionStatusUpdate': TransactionStatusUpdate.handleFromRust,
  'UnsignedTransactionCreatedResponse': UnsignedTransactionCreatedResponse.handleFromRust,
  'TransactionSignedOfflineResponse': TransactionSignedOfflineResponse.handleFromRust,
  'KeyImagesExportedResponse': KeyImagesExportedResponse.handleFromRust,
  'KeyImagesImportedResponse': KeyImagesImportedResponse.handleFromRust,
};
